server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5435
  name: "rtsa_raw"
  user: "rtsa_user"
  password: "rtsa_password"
  pool_size: 10
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 300s

kafka:
  brokers:
    - "localhost:9092"
  topics:
    sentiment_analysis: "sentiment_analysis_topic"
    aggregation: "aggregation_topic"
    alert: "alert_topic"
  producer:
    retry_max: 3
    retry_backoff: 100ms
    flush_frequency: 100ms
    batch_size: 100

rate_limit:
  requests_per_second: 100
  burst_size: 200
  cleanup_interval: 60s

logging:
  level: "INFO"
  format: "json"
  output: "stdout"

health:
  check_interval: 30s
  timeout: 5s

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

webhooks:
  timeout: 30s
  max_body_size: 10485760  # 10MB
  validation:
    enabled: true
    strict_mode: false