apiVersion: 1

datasources:
  - name: RTSA Analytics
    type: postgres
    access: proxy
    url: psql-analytics:5432
    database: rtsa_analytics
    user: rtsa_user
    secureJsonData:
      password: rtsa_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
    isDefault: true

  - name: RTSA Logging
    type: postgres
    access: proxy
    url: psql-logs:5432
    database: rtsa_logging
    user: rtsa_user
    secureJsonData:
      password: rtsa_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false

  - name: RTSA Raw Data
    type: postgres
    access: proxy
    url: psql-raw:5432
    database: rtsa_raw
    user: rtsa_user
    secureJsonData:
      password: rtsa_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false